trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: 'dist'
  nodeVersion: '18.x'  # Asegúrate que esta versión sea compatible con tu código

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Instalar Node.js'

- script: |
    npm install
  displayName: 'Instalar dependencias'

- script: |
    npm run build
  displayName: 'Construir aplicación (npm run build)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/$(buildDir)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copiar archivos de la build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artefactos'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'cloudasturiaspoc'  # Cambia esto por el nombre de tu "Service Connection"
    appType: 'webApp'
    appName: 'Alexia-Putellas'              # Cambia esto por el nombre de tu App Service en Azure
    package: '$(Build.ArtifactStagingDirectory)/*/.zip'
  displayName: 'Desplegar a Azure Web App'